### ISSUE TITLE
`@material-ui/styles` is missing

### ISSUE THREAD

**Issue by Mobilpadde** [vivienneobrien/search-anything#1]
Please add `@material-ui/styles` as a dependency in `package.json`, as it seems to be missing 🙃 

Best of luck,
Mads Cordes

**Comment by vivienneobrien** [comment]
<img width="735" alt="Screen Shot 2021-07-13 at 10 27 04" src="https://user-images.githubusercontent.com/52012478/125427844-a6521304-b8ed-453d-ad51-2a8c66e6cde5.png">


Thank you, I have just added it now

**Comment by Mobilpadde** [comment]
Great!
