### ISSUE TITLE
Stay consistent with one package-manager

### ISSUE THREAD

**Issue by Mobilpadde** [vivienneobrien/search-anything#2]
I can see you both have a `yarn.lock` and `package-lock.json`, which seems you're using both `yarn` and `npm` interchangeably.

You'd stay consistent with one of these only 😇

**Comment by vivienneobrien** [comment]
<img width="274" alt="Screen Shot 2021-07-13 at 10 27 58" src="https://user-images.githubusercontent.com/52012478/125428008-5b54415d-a884-46d1-a15a-a9b468d7bf00.png">

Thanks for the feedback Madz! I have removed the yarn.lock from the project. Is this enough to know that I am only using npm as a package manager now?

**Comment by Mobilpadde** [comment]
Seems good to me :+1:
